package dev.alfred.forensics

/** Presentation criteria for the pinned reference method; never executable scoring. */
internal object ReportRules {
    val definitions = linkedMapOf(
        "R01" to ("Low bandwidth" to "Cutoff below both 85% of Nyquist and 18.5 kHz adds 2 lossy points."),
        "R02" to ("Abrupt spectral edge" to "Sharpness above 15 dB/bin, or cliff above 35 dB with cutoff below 93% of Nyquist, adds 3 lossy points. Otherwise sharpness above 8 or cliff above 20 adds 1."),
        "R03" to ("Very low HF magnitude" to "HF magnitude ratio below 0.005 adds 1 lossy point. This is a magnitude ratio, not an energy ratio."),
        "R04" to ("Above-cutoff noise" to "Reference FFT-magnitude noise below −70 dB adds 3 lossy points; otherwise below −40 dB adds 1. This scale is not dBFS."),
        "R05" to ("Stable low cutoff" to "Cutoff below 85% of Nyquist together with cutoff variance below 1,000 Hz² adds 1 lossy point."),
        "R06" to ("Banding / side evidence" to "Banding above 0.92 together with cutoff below 80% of Nyquist adds 1 lossy point; side evidence above 0.60 adds 2."),
        "R07" to ("Broadband natural evidence" to "For non-DSD spectra, three tests add one natural point each: HF ratio above 0.05 with cutoff above 85% Nyquist; noise above −50 on its reference scale; entropy above 8.5 bits with cutoff above 85% Nyquist."),
        "R08" to ("Smoothness / variation evidence" to "One natural point each for sharpness below 5 dB/bin; variance above 100,000 Hz² for non-DSD (or above 10,000 with cutoff above 85% Nyquist in the other branch); side evidence below 0.2."),
        "R09" to ("Initial heuristic combination" to "Subtract natural from lossy points, floor the net at zero, multiply by 45/14, then use the stored ties-to-even rounded heuristic. The recorded net and initial heuristic are separate from later main-score adjustments."),
        "R10" to ("Sample-rate conversion" to "An ordered resampling hit adds 45 to the reference main score."),
        "R11" to ("Header-based score overrides" to "Duration +20 and bitrate +25 overrides are excluded by the reference contract. Retained header observations are not negative detector evidence."),
        "R12" to ("Preceding-energy evidence" to "This rule first requires cutoff below 21 kHz or an MP3 profile. Eligible preceding-energy evidence above 10% adds 15, otherwise at least 5% adds 10. A large scalar alone cannot bypass the gate."),
        "R13" to ("Band-correlation override" to "The negated absolute-band-correlation override is excluded by contract. The excluded branch would use above 0.5 / at least 0.3; it does not support a mirroring finding under this contract."),
        "R14" to ("Comb evidence" to "The psychoacoustic gate and at least two qualifying comb peaks are required to add 10."),
        "R15" to ("Cassette candidate construction" to "Cutoff below 19 kHz is required. Hiss above −55 dBFS with correlation below 0.2 adds 30 candidate points; slope strictly between −6 and −3 dB/kHz adds 20, below −10 subtracts 20; no comb adds 15; cutoff standard deviation strictly between 50 and 300 Hz adds 15, below 30 subtracts 10; floor candidate score at zero."),
        "R16" to ("Cassette candidate effect" to "Cassette candidate score at least 30 with hiss subtracts 40 from main score and selectively vetoes downstream rules. Not a proof of tape origin."),
        "R17" to ("High-rate bandwidth limitation" to "Requires no resampling hit, sample rate at least 88.2 kHz, positive cutoff below 60% Nyquist, cliff above 25 dB and measured void below −80 dBFS; adds 20."),
        "R18" to ("Repeated spectral wall" to "Adaptive wall may rise from 16.5 kHz to cutoff +400 Hz when cliff exceeds 30 dB, void is below −85 or a fingerprint matches, no resampling wall is present and cutoff is below 22.5 kHz. A qualifying positive at-least-half vote on eligible excerpts adds 55. Only eligible excerpts participate in the recorded vote."),
        "R19" to ("Single anomalous region" to "With no majority wall or cassette veto, one unique anomalous region with cliff above 35 dB and nearest fingerprint adds 25."),
        "R20" to ("Multiple anomalous regions" to "Two or more unique regions add 30; four or more add 40; any qualifying void adds 25; a median fingerprint adds 15, subject to recorded applicability/vetoes."),
        "R21" to ("Strong silence-band ratio" to "At least 2 seconds of qualifying silence and measured HF ratio above 0.3 add 50 and take an early return. This requires the silence-band ratio specifically."),
        "R22" to ("Silence / vinyl evidence" to "Noise below −70 with cutoff below 22.5 kHz and cliff above 25 adds 20. Otherwise noise at least −70, correlation below 0.3 and temporal standard deviation below 5 support the vinyl candidate and subtract 40; 5–50 clicks/minute can subtract another 10."),
        "R23" to ("Broadband counter-evidence" to "With no cassette/majority-wall/resampling evidence, wall at most 16.5 kHz, cutoff above 85% Nyquist and silence ratio from zero up to but excluding 0.15, subtract 30 from main score."),
        "R24" to ("Fingerprint plus strong edge" to "Fingerprint match together with void below −85 or cliff above 30 adds 10, subject to recorded source vetoes."),
        "R25" to ("Low spectral bound" to "At sample rates at least 40 kHz, a positive bound below 16.5 kHz adds 25, subject to recorded source vetoes."),
        "R26" to ("Phase with low sharp cutoff" to "Cutoff below both 85% Nyquist and 22.5 kHz, cliff above 25 dB and phase entropy above 4.5 bits add 10."),
        "R27" to ("Spectral sparsity" to "Cutoff below 95% Nyquist and sparsity above 0.30 add 10."),
        "R28" to ("Independent high-frequency envelope" to "Cutoff above 16.5 kHz, positive bound more than 2 kHz below cutoff and envelope correlation below 0.15 add 15. Added noise is only one possible explanation."),
        "R29" to ("AAC fingerprint" to "At 44.1/48 kHz without source veto, fingerprint at least 0.10 adds 55; otherwise at least 0.06 adds 15."),
        "R30" to ("Vorbis fingerprint" to "At 44.1/48 kHz, fingerprint at least 0.03 raises main score to at least 55, independently of the source veto."),
        "R31" to ("Final reference classification" to "Clamp stored main score to 0–100. The pinned classifier considers parsed lossy codec first, then score at least 86 before resampling/fake branches, then 55/31/11 thresholds. The final qualified summary is the stored classifier output."),
        "R32" to ("MQA certainty override" to "The legacy known-codec / score-100 MQA certainty override is excluded by contract. Sync observations remain separately reportable."),
        "R33" to ("Independent depth interpretation" to "Tests padding of at least eight claimed bits, reduced exercised precision, masked floor above −86 dBFS, floor below −102, and a flat floor at or below −89 with at least 24 declared bits. These per-channel interpretations use at most the first 30 seconds and add no main ancestry points."),
        "R34" to ("Descriptive interpretations" to "Stored scalar interpretations are audit/descriptive outputs. Missing values stay unavailable; native units, normalisation and ReplayGain add no ancestry points. These descriptive measurements do not add ancestry points."),
    )
    val featureNames = linkedMapOf(
        "aac" to "AAC fingerprint",
        "adaptive_wall" to "Adaptive wall",
        "attacks" to "Attack observations",
        "banding" to "Banding",
        "bound" to "Spectral bound",
        "cassette_hiss" to "Cassette hiss candidate",
        "cassette_score" to "Cassette candidate points",
        "clicks" to "Click observations",
        "cliff" to "Spectral cliff",
        "comb" to "Comb pattern",
        "cutoff" to "Reference cutoff",
        "depth_claimed" to "Declared precision",
        "depth_color" to "Reference floor color",
        "depth_floor" to "Reference depth floor",
        "dsd_spectrum" to "DSD-shaped spectrum",
        "effective_bits_channel_0" to "Channel 1 exercised bits",
        "effective_bits_channel_1" to "Channel 2 exercised bits",
        "entropy" to "Spectral entropy",
        "envelope" to "HF envelope correlation",
        "header_bitrate" to "Header bitrate mismatch",
        "header_duration" to "Header duration mismatch",
        "hf" to "HF magnitude ratio",
        "hiss" to "Hiss level",
        "hiss_corr" to "Hiss correlation",
        "mqa" to "MQA sync observation",
        "noise" to "Above-cutoff FFT magnitude",
        "phase" to "Phase entropy",
        "preecho" to "Preceding-energy scalar",
        "rate" to "Sample rate",
        "resample" to "Resampling source-rate hit",
        "resample_wall" to "Resampling wall",
        "segment_majority" to "Majority spectral wall",
        "sharpness" to "Edge sharpness",
        "side" to "Side-channel evidence",
        "silence_ratio" to "Silence-band HF ratio",
        "silence_seconds" to "Qualifying silence",
        "slope" to "HF slope",
        "sparsity" to "Spectral sparsity",
        "variance" to "Cutoff variance",
        "vinyl_candidate" to "Vinyl candidate",
        "vinyl_corr" to "Vinyl noise correlation",
        "vinyl_noise" to "Vinyl noise level",
        "vinyl_variance" to "Vinyl temporal deviation",
        "void" to "High-frequency void level",
        "vorbis" to "Vorbis fingerprint",
    )
    val candidates = linkedMapOf(
        "cassette" to "Cassette-like source",
        "vinyl" to "Vinyl-like noise",
        "bandwidth" to "Bandwidth-limited high-rate source",
        "resampling" to "Sample-rate conversion",
        "independent_hf" to "Independent high-frequency envelope",
    )
    val states = linkedMapOf(
        "applied" to "Applied",
        "not_triggered" to "Not triggered",
        "excluded_by_contract" to "Excluded by reference contract",
        "unavailable" to "Unavailable",
        "vetoed" to "Vetoed by another rule",
    )
    val supplements = mapOf(
        "R02" to listOf("cliff"), "R05" to listOf("variance"), "R06" to listOf("banding"),
        "R12" to listOf("preecho"), "R14" to listOf("comb"), "R15" to listOf("hiss", "hiss_corr", "slope", "variance"),
        "R17" to listOf("rate", "cutoff", "cliff", "void", "resample"),
        "R22" to listOf("noise", "vinyl_noise", "vinyl_corr", "vinyl_variance", "clicks"),
        "R24" to listOf("void", "cliff"), "R26" to listOf("cliff", "phase"),
        "R27" to listOf("sparsity"), "R28" to listOf("envelope")
    )
}
